import type { RemoteDispatchResponse } from '../../shared/remote-validation'
import { RemoteSecurityError, type AuthorizedRemoteRequest } from './authorization-service'
import { RemoteStore } from './remote-store'

export interface IdempotentExecutionResult {
  replayed: boolean
  response: RemoteDispatchResponse
}

/**
 * Claims the durable receipt before invoking a side effect. A crash leaves an
 * `uncertain` receipt on the next start; it is never silently re-executed.
 * Structured task actions should additionally pass the same requestId into the
 * task ledger/adapter so the final side effect has end-to-end idempotency.
 */
export class RemoteIdempotencyService {
  constructor(private readonly store: RemoteStore) {}

  async execute(
    authorized: AuthorizedRemoteRequest,
    operation: () => Promise<RemoteDispatchResponse>,
  ): Promise<IdempotentExecutionResult> {
    const { device, verified } = authorized
    const claim = this.store.claimRequest({
      deviceId: device.id,
      requestId: verified.envelope.headers.requestId,
      operationHash: verified.operationHash,
      createIfMissing: authorized.nonceFresh,
    })
    if (claim.outcome === 'replay') {
      return {
        replayed: true,
        response: { status: claim.response.status, body: claim.response.body },
      }
    }
    if (claim.outcome === 'conflict') {
      throw new RemoteSecurityError(409, 'IDEMPOTENCY_CONFLICT', 'Request ID was already used for a different action.')
    }
    if (claim.outcome === 'missing') {
      throw new RemoteSecurityError(409, 'REPLAY_DETECTED', 'Remote request was already received.')
    }
    if (claim.outcome === 'in_progress' || claim.outcome === 'uncertain') {
      throw new RemoteSecurityError(
        409,
        claim.outcome === 'uncertain' ? 'ACTION_RESULT_UNCERTAIN' : 'ACTION_IN_PROGRESS',
        claim.outcome === 'uncertain'
          ? 'The earlier action result is uncertain and will not be repeated automatically.'
          : 'The same action is already in progress.',
      )
    }

    try {
      let response = await operation()
      if (response.headers && Object.keys(response.headers).length > 0) {
        // Receipts intentionally persist only public status/body. Security
        // headers are regenerated by the HTTP Gateway on replay.
        response = { ...response, headers: undefined }
      }
      const stored = this.store.completeRequest(
        device.id,
        verified.envelope.headers.requestId,
        { status: response.status, body: response.body },
      )
      return { replayed: false, response: { status: stored.status, body: stored.body } }
    } catch (error) {
      this.store.markRequestUncertain(device.id, verified.envelope.headers.requestId)
      throw error
    }
  }
}
