/**
 * Redacted desktop-facing state for the Mobile Remote settings screen.
 *
 * This module intentionally has no Supabase session or device credential
 * fields. Access/refresh tokens, private keys, pairing secrets, and raw audit
 * payloads must remain in the long-running Core.
 */

export type RemoteSettingsPhase =
  | 'unconfigured'
  | 'signed-out'
  | 'verification-required'
  | 'secure-storage-unavailable'
  | 'disabled'
  | 'starting'
  | 'ready'
  | 'degraded'
  | 'password-recovery'

export type RemoteCheckState = 'pass' | 'warning' | 'fail' | 'pending' | 'not-run'
export type RemoteDeviceState = 'active' | 'pending-cloud-sync' | 'revoked'
export type RemotePairingStage = 'showing-code' | 'awaiting-computer-confirmation'

export interface RemoteAccountView {
  /** Null while a newly registered email is awaiting confirmation. */
  userId: string | null
  email: string
  nickname: string
  emailVerified: boolean
}

export interface RemoteAgentPermissionSet {
  viewStatus: boolean
  viewEvents: boolean
  message: boolean
  approve: boolean
  interrupt: boolean
}

export interface RemoteAgentPermissionView {
  agentId: string
  agentName: string
  projectName: string
  color: string
  permissions: RemoteAgentPermissionSet
  pendingCloudSync: boolean
}

export interface RemoteDeviceView {
  deviceId: string
  displayName: string
  platform: 'android' | 'ios' | 'unknown'
  state: RemoteDeviceState
  pairedAt: string
  lastSeenAt: string | null
}

export interface RemotePairingView {
  pairingId: string
  stage: RemotePairingStage
  /** A data URL generated by Core; never a renderer-created long-term key. */
  qrDataUrl: string
  sas: string
  expiresAt: string
  candidateDeviceName: string | null
}

export interface RemoteServiceCheck {
  id: 'secure-storage' | 'core' | 'gateway' | 'tunnel' | 'https'
  label: string
  state: RemoteCheckState
  detail: string
  checkedAt: string | null
}

export interface RemoteGatewayView {
  enabled: boolean
  localAddress: string | null
  publicBaseUrl: string | null
  gatewayPid: number | null
  tunnelActive: boolean
  lastReachableAt: string | null
}

export interface RemoteWorkstationView {
  workstationId: string
  displayName: string
  pendingCloudSync: boolean
}

export interface RemoteSettingsCapabilities {
  canRegister: boolean
  canSignIn: boolean
  canEnable: boolean
  canPair: boolean
  canRunDoctor: boolean
  canRemoveWorkstation: boolean
}

export interface RemoteSettingsState {
  phase: RemoteSettingsPhase
  message: string
  secureStorageReady: boolean
  account: RemoteAccountView | null
  workstation: RemoteWorkstationView | null
  gateway: RemoteGatewayView
  agents: RemoteAgentPermissionView[]
  devices: RemoteDeviceView[]
  pairing: RemotePairingView | null
  checks: RemoteServiceCheck[]
  capabilities: RemoteSettingsCapabilities
}

export interface RemoteSignUpInput {
  email: string
  password: string
  nickname: string
}

export interface RemoteSignInInput {
  email: string
  password: string
}

export interface RemoteCompletePasswordRecoveryInput {
  newPassword: string
}

export interface RemotePairingDecisionInput {
  pairingId: string
  approve: boolean
}

export interface RemoteAgentPermissionInput {
  agentId: string
  permissions: RemoteAgentPermissionSet
}

export interface RemoteRemoveWorkstationInput {
  confirmationName: string
}
